### ISSUE TITLE
Icons not matching games

### ISSUE THREAD

**Issue by TwoTracks** [pascl/pbPSCBSLauncherGenerator#5]
Game icons don't seem to match any of my scanned games which makes this software unusable

**Comment by pascl** [comment]
All of them or only some ?

Did you copy the gamelists folder as mentioned in the readme to have pictures ?

Did you scan for a known system (not all are present in the gamelists) ?

**Comment by TwoTracks** [comment]
I have scrapped my own playlist for the one not included

Not all of them only ones with a lot of games seem to be affected
 
Yes I copied the games list linked on your page

Yes most of my games have icons they just don't match

![Capture](https://user-images.githubusercontent.com/31736974/69013394-30a37b80-0977-11ea-8705-6a5be46e9d69.PNG)
 up

**Comment by pascl** [comment]
I had the good picture for this particular game when I scanned a fullset folder. Are you sure your gamelist.xml is ok ? It seems you have a bad year too (or another format than expected maybe).

I know that the scraping is not perfect (skip conflicts and take the first one found) but all would be right or wrong. Here you have the right name but the wrong picture. I am a bit confused...

**Comment by TwoTracks** [comment]
Heres a picture of my gameslist but everything seems fine not sure whats wrong

![Capture](https://user-images.githubusercontent.com/31736974/69014681-bda10180-0984-11ea-8984-e636a3a750d8.PNG)

**Comment by pascl** [comment]
And the contents of the jpg files are ok ?

**Comment by TwoTracks** [comment]
They seem to look fine, here's a screenshot 

![Capture](https://user-images.githubusercontent.com/31736974/69016400-ee3d6700-0995-11ea-8617-d4e29bd17ff5.PNG)

**Comment by pascl** [comment]
I may understand what happened. Can you send me a copy of your gamelist to check if I fixed it please ?

**Comment by pascl** [comment]
The way the app reads the xml has been modified in the last release (0.41). It should be better now.
