### ISSUE TITLE
loading games

### ISSUE THREAD

**Issue by TwoTracks** [pascl/pbPSCBSLauncherGenerator#7]
I'm having trouble loading games from any other console other than GBA or GBC I don't know if its something I'm doing wrong but I've look so hard and was wondering if you could help me solve what I am doing wrong? Thank you

![image](https://user-images.githubusercontent.com/31736974/70064595-b5ca9980-15e1-11ea-990a-811af9a98567.png)

**Comment by pascl** [comment]
Probably the same issue there:
https://github.com/pascl/pbPSCReAlpha/issues/29

All cores need to be uncompressed.
If some cores work, they may be uncompressed already.

**Comment by TwoTracks** [comment]
I also have a problem running DS would that be a similar issue?

**Comment by pascl** [comment]
For ds, there is an error during file generation. I have fixed it but not released yet.

**Comment by TwoTracks** [comment]
Thank you so much can't wait for an update :D

**Comment by pascl** [comment]
Workaround for now:

In launch.sh of your ds games, replace $runtime_log_path by /media/logs

**Comment by TwoTracks** [comment]
Thank you so much

**Comment by pascl** [comment]
The 0.41 release fixes the ds files.
